
import { Geist } from "next/font/google";
import { Raleway } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});



export const metadata = {
  title: "Micaela's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/micaela-logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
