
import { Geist, Geist_Mono } from "next/font/google";
import { Raleway, Ghaista } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const ghaista = Ghaista({
  variable: "--font-ghaista",
  subsets: ["latin"],
});



export const metadata = {
  title: "Micaela Valmores",
  description: "Generated by create next app",
  icons: {
    icon: "/logos/micaela-logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${ghaista.variable}`}>
        {children}
      </body>
    </html>
  );
}
